package org.juice4j.caching;

/**
 * Defines a common behavior to the generation of cache element key component strings.
 * @see {@link ElementKeyGenerator} - documentation about this API
 * @param <T> Type of the object expected to be parsed into a component key string.
 * @author Rafael Noronha
 */
public interface ElementKeyComponentGenerator<TK> {
	
	/**
	 * Returns a static representation for the key component generated by this object.
	 * @return The static representation string.
	 */	
	String staticRepresentation();

	/**
	 * Generates a string for this element key component.
	 * @param obj Object that will be parsed into a string.
	 * @return Generated string.
	 */		
	String generate(TK typedKeyObject);
}
